name: Test matrix action status

on:
  push:
    branches: main

jobs:
  foo:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        index: [1, 2]
    steps:
      - run: |
          if [ "${{ matrix.index }}" == "1" ]
          then
            echo "error"
            exit 1
          else
            echo "success"
          fi

  check_status:
    runs-on: ubuntu-latest
    needs: foo
    if: ${{ always() && needs.foo.result == 'failure' }}
    steps:
      - run: echo ${{ needs.foo.result }}

