name: Test matrix action status

on:
  push:
    branches: main

jobs:
  foo:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        index: [1, 2]
    steps:
      - run: |
          ([ "${{ matrix.index }}" == "1" ] && echo "error" && exit 1) || echo "success"

  check_status:
    runs-on: ubuntu-latest
    needs: foo
    if: ${{ always() && needs.foo.result == 'failure' }}
    steps:
      - run: echo ${{ needs.foo.result }}

