name: Test matrix action status

on:
  push:
    branches: main

jobs:
  foo:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        index: [1, 2]
    steps:
      - run: |
          echo "error"
          exit 1

  check_status:
    runs-on: ubuntu-latest
    needs: foo
    if: always()
    steps:
      - run: echo ${{ needs.foo.result }}

